USE ODS;

SELECT COUNT(AG.ID_AGENTE_CC) TOTAL_AGENTES
, COUNT(CA.ID_CANAL) TOTAL_CANALES
, COUNT(CICL.ID_CICLO_FACTURACION) TOTAL_CICLO_FACTURACION
, COUNT(CIUD.ID_CIUDAD_ESTADO) TOTAL_CIUDADES
, COUNT(COMP.ID_COMPANYA) TOTAL_COMPANYAS
, COUNT(DEP.ID_DEPARTAMENTO_CC) TOTAL_DEPARTAMENTOS
, COUNT(MET.ID_METODO_PAGO) TOTAL_METODOS_PAGO
, COUNT(PAI.ID_PAIS) TOTAL_PAISES
, COUNT(PROD.ID_PRODUCTO) TOTAL_PRODUCTOS
, COUNT(PROF.ID_PROFESION) TOTAL_PROFESIONES
, COUNT(SEX.ID_SEXO) TOTAL_GENERO
, COUNT(CL.ID_CLIENTE) TOTAL_CLIENTES
, COUNT(DIR.ID_DIRECCION) TOTAL_DIRECCIONES
, COUNT(FAC.ID_FACTURA) TOTAL_FACTURAS
, COUNT(LLAM.ID_LLAMADA) TOTAL_LLAMADAS
, COUNT(SERV.ID_SERVICIO) TOTAL_SERVICIOS
FROM ODS_DM_AGENTES_CC AG, ODS_DM_CANALES CA, ODS_DM_CICLOS_FACTURACION CICL, ODS_DM_CIUDADES_ESTADOS CIUD, ODS_DM_COMPANYAS COMP, ODS_DM_DEPARTAMENTOS_CC DEP,
ODS_DM_METODOS_PAGO MET, ODS_DM_PAISES PAI, ODS_DM_PRODUCTOS PROD, ODS_DM_PROFESIONES PROF, ODS_DM_SEXOS SEX, ODS_HC_CLIENTES CL, ODS_HC_DIRECCIONES DIR,
ODS_HC_FACTURAS FAC, ODS_HC_LLAMADAS LLAM, ODS_HC_SERVICIOS SERV;

SELECT table_name,table_rows
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGE';

SELECT COUNT(*)
FROM ODS_HC_CLIENTES;

SELECT COUNT(*)
FROM ODS_HC_FACTURAS;

SELECT COUNT(*)
FROM STAGE.STG_FACTURAS_FCT;

SELECT COUNT(ID_CLIENTE)
FROM ODS.ODS_HC_CLIENTES;

SELECT COUNT(CUSTOMER_ID)
FROM STAGE.STG_CLIENTES_CRM;

SELECT CONCAT(
    'SELECT "', 
    table_name, 
    '" AS table_name, COUNT(*) AS exact_row_count FROM `', 
    table_schema, 
    '`.`', 
    table_name, 
    '` UNION ' 
) 
FROM INFORMATION_SCHEMA.TABLES 
WHERE table_schema = 'STAGE'; 

SELECT "ODS_DM_AGENTES_CC" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_AGENTES_CC` UNION 
SELECT "ODS_DM_CANALES" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_CANALES` UNION 
SELECT "ODS_DM_CICLOS_FACTURACION" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_CICLOS_FACTURACION` UNION 
SELECT "ODS_DM_CIUDADES_ESTADOS" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_CIUDADES_ESTADOS` UNION 
SELECT "ODS_DM_COMPANYAS" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_COMPANYAS` UNION 
SELECT "ODS_DM_DEPARTAMENTOS_CC" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_DEPARTAMENTOS_CC` UNION 
SELECT "ODS_DM_METODOS_PAGO" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_METODOS_PAGO` UNION 
SELECT "ODS_DM_PAISES" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_PAISES` UNION 
SELECT "ODS_DM_PRODUCTOS" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_PRODUCTOS` UNION 
SELECT "ODS_DM_PROFESIONES" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_PROFESIONES` UNION 
SELECT "ODS_DM_SEXOS" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_DM_SEXOS` UNION 
SELECT "ODS_HC_CLIENTES" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_HC_CLIENTES` UNION 
SELECT "ODS_HC_DIRECCIONES" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_HC_DIRECCIONES` UNION 
SELECT "ODS_HC_FACTURAS" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_HC_FACTURAS` UNION 
SELECT "ODS_HC_LLAMADAS" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_HC_LLAMADAS` UNION 
SELECT "ODS_HC_SERVICIOS" AS table_name, COUNT(*) AS exact_row_count FROM `ODS`.`ODS_HC_SERVICIOS`;

SELECT "STG_CLIENTES_CRM" AS table_name, COUNT(*) AS exact_row_count FROM `STAGE`.`STG_CLIENTES_CRM` UNION 
SELECT "STG_CONTACTOS_IVR" AS table_name, COUNT(*) AS exact_row_count FROM `STAGE`.`STG_CONTACTOS_IVR` UNION 
SELECT "STG_FACTURAS_FCT" AS table_name, COUNT(*) AS exact_row_count FROM `STAGE`.`STG_FACTURAS_FCT` UNION 
SELECT "STG_PRODUCTOS_CRM" AS table_name, COUNT(*) AS exact_row_count FROM `STAGE`.`STG_PRODUCTOS_CRM`;

SELECT *
FROM ODS_HC_DIRECCIONES; 

SELECT *
FROM ODS_DM_CIUDADES_ESTADOS;

ALTER TABLE ODS_HC_DIRECCIONES DROP NOMBRE_VIA;
ALTER TABLE ODS_HC_DIRECCIONES DROP NUM_VIA;

ALTER TABLE ODS_HC_DIRECCIONES ADD ( NOMBRE_VIA VARCHAR(512) default '', NUM_VIA VARCHAR(512) default '');

ANALYZE TABLE ODS_HC_DIRECCIONES;

UPDATE ODS_HC_FACTURAS ODS
INNER JOIN TMP_CLIENTES_NOT_EXIST TMP ON ODS.ID_CLIENTE = TMP.ID_CLIENTE
SET ODS.ID_CLIENTE = -1;

UPDATE ODS_HC_DIRECCIONES DIR
SET NOMBRE_VIA =  SUBSTRING_INDEX(SUBSTRING_INDEX(DIR.DE_DIRECCION, ' ', 1), ' ', -1),
NUM_VIA = TRIM( SUBSTR(DIR.DE_DIRECCION, LOCATE(' ', DIR.DE_DIRECCION)) );

SELECT * 
FROM ODS_HC_DIRECCIONES;
