USE DDS;

DROP TABLE IF EXISTS DDS_DM_ID_DIA_NUM;

CREATE TABLE DDS_DM_ID_DIA_NUM
(ID_DIA_NUM BIGINT
, FECHA_DS DATE
, DIA_ID INT
, DIA_SEMANA_ID INT
, DIA_SEMANA_DS VARCHAR(32)
, MES_ID INT
, MES_DS VARCHAR(32)
, ANYO4_ID INT
, ANYO2_ID INT
, Q_DS VARCHAR(8)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

INSERT INTO DDS_DM_ID_DIA_NUM
select DATE_FORMAT('1900-01-01','%Y%m%d') ID_DIA_NUM 
, DATE_FORMAT('1900-01-01','%Y-%m-%d') FECHA_DS
, DATE_FORMAT('1900-01-01','%d') DIA_ID
, DATE_FORMAT('1900-01-01','%w') DIA_SEMANA_ID
, DATE_FORMAT('1900-01-01','%W') DIA_SEMANA_DS
, DATE_FORMAT('1900-01-01','%m') MES_ID
, DATE_FORMAT('1900-01-01','%M') MES_DS
, DATE_FORMAT('1900-01-01','%Y') ANYO4_ID
, DATE_FORMAT('1900-01-01','%y') ANYO2_ID
, CONCAT('Q',QUARTER(DATE_FORMAT('1900-01-01','%Y-%m-%d'))) CUATRIMESTRE_DS
	, NOW(), NOW();
    
COMMIT;


select * from DDS_DM_ID_DIA_NUM;

DROP PROCEDURE IF EXISTS insert_ini_id_dia;

DELIMITER $$

CREATE PROCEDURE insert_ini_id_dia(d date)
BEGIN
SET @i='1900-01-01';
REPEAT
	SET @i=ADDDATE(DATE_FORMAT(@i,'%Y-%m-%d'),INTERVAL 1 DAY);
    INSERT INTO DDS_DM_ID_DIA_NUM
			select DATE_FORMAT(@i,'%Y%m%d') ID_DIA_NUM 
				, DATE_FORMAT(@i,'%Y-%m-%d') FECHA_DS
				, DATE_FORMAT(@i,'%d') DIA_ID
				, DATE_FORMAT(@i,'%w') DIA_SEMANA_ID
				, DATE_FORMAT(@i,'%W') DIA_SEMANA_DS
				, DATE_FORMAT(@i,'%m') MES_ID
				, DATE_FORMAT(@i,'%M') MES_DS
				, DATE_FORMAT(@i,'%Y') ANYO4_ID
				, DATE_FORMAT(@i,'%y') ANYO2_ID
				, CONCAT('Q',QUARTER(DATE_FORMAT(@i,'%Y-%m-%d'))) CUATRIMESTRE_DS
				, NOW(), NOW();
	COMMIT;
UNTIL @i>=d END REPEAT;
END; $$

CALL insert_ini_id_dia('2020-12-31');

SELECT * FROM DDS_DM_ID_DIA_NUM;


