# LLAMADAS
# CREACIÓN DE TABLAS
USE ODS;

#ALTER TABLE ODS_HC_LLAMADAS DROP FOREIGN KEY fk_cl
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS ODS_HC_LLAMADAS;

CREATE TABLE ODS_HC_LLAMADAS
(ID_LLAMADA INT AUTO_INCREMENT NOT NULL PRIMARY KEY
, ID_IVR INT
, TELEFONO_LLAMADA BIGINT
, ID_CLIENTE INT
, FC_INICIO_LLAMADA DATETIME
, FC_FIN_LLAMADA DATETIME
, ID_DEPARTAMENTO_CC INT
, FLG_TRANSFERIDO TINYINT
, ID_AGENTE_CC INT
, FC_INSERT DATETIME
, FC_MODIFICATION DATETIME);

DROP TABLE IF EXISTS ODS_DM_DEPARTAMENTOS_CC;

CREATE TABLE ODS_DM_DEPARTAMENTOS_CC 
(ID_DEPARTAMENTO_CC INT AUTO_INCREMENT NOT NULL PRIMARY KEY
, DE_DEPARTAMENTO_CC VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_AGENTES_CC;

CREATE TABLE ODS_DM_AGENTES_CC
(ID_AGENTE_CC INT AUTO_INCREMENT PRIMARY KEY
, DE_AGENTE_CC VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);

# CREACIÓN DE FK

ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_lla_cli_idx (ID_CLIENTE ASC);
#ALTER TABLE ODS_HC_CLIENTES MODIFY COLUMN ID_SEXO INT(10) UNSIGNED;
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_lla_cli FOREIGN KEY(ID_CLIENTE)
   REFERENCES ODS_HC_CLIENTES(ID_CLIENTE);
   
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_lla_dep_idx(ID_DEPARTAMENTO_CC ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_lla_dep FOREIGN KEY (ID_DEPARTAMENTO_CC)
REFERENCES ODS_DM_DEPARTAMENTOS_CC(ID_DEPARTAMENTO_CC);   
   
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_lla_age_idx(ID_AGENTE_CC ASC);
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_lla_age FOREIGN KEY (ID_AGENTE_CC)
REFERENCES ODS_DM_AGENTES_CC(ID_AGENTE_CC);

# POBLAMOS EL MODELO

INSERT INTO ODS_DM_DEPARTAMENTOS_CC (DE_DEPARTAMENTO_CC, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(SERVICE)) DE_DEPARTAMENTO_CC
, NOW(),NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE TRIM(SERVICE)<>'';
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (-1,'DESCONOCIDO', NOW(),NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (-2,'NO APLICA', NOW(),NOW());
COMMIT;
ANALYZE TABLE ODS_DM_DEPARTAMENTOS_CC;

SELECT *
FROM ODS.ODS_DM_DEPARTAMENTOS_CC;

INSERT INTO ODS_DM_AGENTES_CC (DE_AGENTE_CC, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(AGENT)) DE_AGENTE_CC
, NOW(),NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE TRIM(AGENT)<>'';
INSERT INTO ODS_DM_AGENTES_CC VALUES (-1,'DESCONOCIDO', NOW(),NOW());
INSERT INTO ODS_DM_AGENTES_CC VALUES (-2,'NO APLICA', NOW(),NOW());
COMMIT;
ANALYZE TABLE ODS_DM_AGENTES_CC;

SELECT *
FROM ODS.ODS_DM_AGENTES_CC;


SET FOREIGN_KEY_CHECKS=0;

TRUNCATE ODS.ODS_HC_LLAMADAS;


INSERT INTO ODS_HC_LLAMADAS (ID_IVR, TELEFONO_LLAMADA, ID_CLIENTE, FC_INICIO_LLAMADA, FC_FIN_LLAMADA, ID_DEPARTAMENTO_CC, FLG_TRANSFERIDO, ID_AGENTE_CC, FC_INSERT, FC_MODIFICATION)
SELECT ID ID_IVR
, CASE WHEN TRIM(PHONE_NUMBER) <>'' THEN PHONE_NUMBER ELSE -1 END TELEFONO_LLAMADA
, -1
, CASE WHEN TRIM(START_DATETIME)<>'' THEN STR_TO_DATE(LEFT(START_DATETIME,19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_INICIO_LLAMADA
, CASE WHEN TRIM(END_DATETIME)<>'' THEN STR_TO_DATE(LEFT(END_DATETIME,19),'%Y-%m-%d %H:%i:%s') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_FIN_LLAMADA
, DEPT.ID_DEPARTAMENTO_CC ID_DEPARTAMENTO_CC
, CASE WHEN TRIM(FLG_TRANSFER) = 'TRUE' THEN TRUE ELSE FALSE END  FLG_TRANSFERIDO
, AGE.ID_AGENTE_CC ID_AGENTE_CC
, NOW()
, NOW()
FROM STAGE.STG_CONTACTOS_IVR CONTACTOS
LEFT JOIN ODS.ODS_DM_AGENTES_CC AGE ON CASE WHEN TRIM(AGENT)<>'' THEN UPPER(TRIM(CONTACTOS.AGENT)) ELSE 'DESCONOCIDO' END=AGE.DE_AGENTE_CC
LEFT JOIN ODS.ODS_DM_DEPARTAMENTOS_CC DEPT ON CASE WHEN TRIM(SERVICE)<>'' THEN UPPER(TRIM(CONTACTOS.SERVICE)) ELSE 'DESCONOCIDO' END=DEPT.DE_DEPARTAMENTO_CC;

INSERT INTO ODS_HC_LLAMADAS VALUES (-1, -1, -1,-1, STR_TO_DATE('31/12/9999','%d/%m/%Y'), STR_TO_DATE('31/12/9999','%d/%m/%Y'),-1,0,-1,NOW(), NOW());
INSERT INTO ODS_HC_LLAMADAS VALUES (-2, -2, -2, -2, STR_TO_DATE('31/12/9999','%d/%m/%Y'), STR_TO_DATE('31/12/9999','%d/%m/%Y'),-2,0,-2,NOW(), NOW());

COMMIT;

SELECT ID
FROM STAGE.STG_CONTACTOS_IVR;

SET FOREIGN_KEY_CHECKS=1;

SELECT COUNT(*)
FROM ODS.ODS_HC_LLAMADAS;