USE STAGE;

SELECT * 
FROM STG_FACTURAS_FCT;

SELECT COUNT(*) TOTAL_REGISTROS, 
SUM(CASE WHEN BILL_REF_NO IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_BILL_REF_NO,
 COUNT( DISTINCT CASE WHEN BILL_REF_NO IS NOT NULL AND BILL_REF_NO <> '' THEN BILL_REF_NO ELSE 0 END) as TOTAL_DISTINTOS_BILL_REF
, SUM(CASE WHEN CUSTOMER_ID IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_CUSTOMER_ID
, COUNT(DISTINCT CASE WHEN CUSTOMER_ID IS NOT NULL AND CUSTOMER_ID <> '' THEN CUSTOMER_ID ELSE 0 END) as TOTAL_DISTINTOS_CUSTOMER_ID
, SUM(CASE WHEN START_DATE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_START_DATE
, COUNT(DISTINCT CASE WHEN START_DATE IS NOT NULL AND START_DATE <> '' THEN START_DATE ELSE 0 END) as TOTAL_DISTINTOS_START_DATE
, SUM(CASE WHEN END_DATE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_END_DATE
, COUNT(DISTINCT CASE WHEN END_DATE IS NOT NULL AND END_DATE <> '' THEN END_DATE ELSE 0 END) as TOTAL_DISTINTOS_END_DATE
, SUM(CASE WHEN STATEMENT_DATE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_STATEMENT_DATE
, COUNT(DISTINCT CASE WHEN STATEMENT_DATE IS NOT NULL AND STATEMENT_DATE <> '' THEN STATEMENT_DATE ELSE 0 END) as TOTAL_DISTINTOS_STATEMENT_DATE
, SUM(CASE WHEN PAYMENT_DATE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_PAYMENT_DATE
, COUNT(DISTINCT CASE WHEN PAYMENT_DATE IS NOT NULL AND PAYMENT_DATE <> '' THEN PAYMENT_DATE ELSE 0 END) as TOTAL_DISTINTOS_PAYMENT_DATE
, SUM(CASE WHEN BILL_CYCLE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_BILL_CYCLE
, COUNT(DISTINCT CASE WHEN BILL_CYCLE IS NOT NULL AND BILL_CYCLE <> '' THEN BILL_CYCLE ELSE 0 END) as TOTAL_DISTINTOS_BILL_CYCLE
, SUM(CASE WHEN AMOUNT IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_AMOUNT
, COUNT(DISTINCT CASE WHEN AMOUNT IS NOT NULL AND AMOUNT <> '' THEN AMOUNT ELSE 0 END) as TOTAL_DISTINTOS_AMOUNT
, SUM(CASE WHEN BILL_METHOD IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_BILL_METHOD
, COUNT(DISTINCT CASE WHEN BILL_METHOD IS NOT NULL AND BILL_METHOD <>  '' THEN BILL_METHOD ELSE 0 END) as TOTAL_DISTINTOS_BILL_METHOD
FROM STAGE.STG_FACTURAS_FCT;


SELECT COUNT(*) TOTAL_REGISTROS, 
SUM(CASE WHEN BILL_REF_NO IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_BILL_REF_NO,
 COUNT( DISTINCT CASE WHEN BILL_REF_NO IS NOT NULL AND BILL_REF_NO <> '' THEN BILL_REF_NO ELSE 0 END) as TOTAL_DISTINTOS_BILL_REF
, SUM(CASE WHEN CUSTOMER_ID IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_CUSTOMER_ID
, COUNT(DISTINCT CASE WHEN CUSTOMER_ID IS NOT NULL AND CUSTOMER_ID <> '' THEN CUSTOMER_ID ELSE 0 END) as TOTAL_DISTINTOS_CUSTOMER_ID
, COUNT(DISTINCT CUSTOMER_ID) as TOTAL_DISTINTOS_CUSTOMER_ID_WITH_NULL
, SUM(CASE WHEN START_DATE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_START_DATE
, COUNT(DISTINCT CASE WHEN START_DATE IS NOT NULL AND START_DATE <> '' THEN START_DATE ELSE 0 END) as TOTAL_DISTINTOS_START_DATE
, SUM(CASE WHEN END_DATE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_END_DATE
, COUNT(DISTINCT CASE WHEN END_DATE IS NOT NULL AND END_DATE <> '' THEN END_DATE ELSE 0 END) as TOTAL_DISTINTOS_END_DATE
, SUM(CASE WHEN STATEMENT_DATE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_STATEMENT_DATE
, COUNT(DISTINCT CASE WHEN STATEMENT_DATE IS NOT NULL AND STATEMENT_DATE <> '' THEN STATEMENT_DATE ELSE 0 END) as TOTAL_DISTINTOS_STATEMENT_DATE
, SUM(CASE WHEN PAYMENT_DATE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_PAYMENT_DATE
, COUNT(DISTINCT CASE WHEN PAYMENT_DATE IS NOT NULL AND PAYMENT_DATE <> '' THEN PAYMENT_DATE ELSE 0 END) as TOTAL_DISTINTOS_PAYMENT_DATE
, SUM(CASE WHEN BILL_CYCLE IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_BILL_CYCLE
, COUNT(DISTINCT CASE WHEN BILL_CYCLE IS NOT NULL AND BILL_CYCLE <> '' THEN BILL_CYCLE ELSE 0 END) as TOTAL_DISTINTOS_BILL_CYCLE
, SUM(CASE WHEN AMOUNT IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_AMOUNT
, COUNT(DISTINCT CASE WHEN AMOUNT IS NOT NULL AND AMOUNT <> '' THEN AMOUNT ELSE 0 END) as TOTAL_DISTINTOS_AMOUNT
, COUNT(DISTINCT AMOUNT) as TOTAL_DISTINTOS_AMOUNT_WITH_NULL
, SUM(CASE WHEN BILL_METHOD IS NOT NULL THEN 1 ELSE 0 END) as TOTAL_BILL_METHOD
, COUNT(DISTINCT CASE WHEN BILL_METHOD IS NOT NULL AND BILL_METHOD <>  '' THEN BILL_METHOD ELSE 0 END) as TOTAL_DISTINTOS_BILL_METHOD
FROM STAGE.STG_FACTURAS_FCT;

SELECT COUNT(*) as TOTAL_REGISTROS,
COUNT(ID) AS TOTAL_ID, COUNT(DISTINCT ID) as TOTAL_DISTINTOS_ID,
COUNT(PHONE_NUMBER) as TOTAL_PHONE_NUMBER, COUNT(DISTINCT PHONE_NUMBER) as TOTAL_DISTINTOS_PHONE_NUMBER,
COUNT(START_DATETIME) as TOTAL_START_DATETIME, COUNT(DISTINCT START_DATETIME) as TOTAL_DISTINTOS_DATETIME,
COUNT(END_DATETIME) as TOTAL_END_DATETIME, COUNT(DISTINCT END_DATETIME) AS TOTAL_DISTINTOS_END_DATETIME,
COUNT(SERVICE) AS TOTAL_SERVICE, COUNT(DISTINCT SERVICE) AS TOTAL_DISTINTOS_SERVICE,
COUNT(FLG_TRANSFER) AS TOTAL_FLG_TRANSFER, COUNT(DISTINCT FLG_TRANSFER) AS TOTAL_DISTINTOS_FLG_TRANSFER,
COUNT(AGENT)  AS TOTAL_AGENT, COUNT(DISTINCT AGENT) as TOTAL_DISTINTOS_AGENT
FROM STG_CONTACTOS_IVR;